load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "cpp-challenge-tests",
    srcs = ["main.cpp"],
    deps = [
        "//main:cpp-challenge-lib",
        "@com_google_googletest//:gtest_main"
    ],

)